<?xml version="1.0" encoding="UTF-8"?>
<Territory xmlns="http://soap.sforce.com/2006/04/metadata">
    <caseAccessLevel>Read</caseAccessLevel>
    <contactAccessLevel>Read</contactAccessLevel>
    <description>Aargau</description>
    <mayForecastManagerShare>false</mayForecastManagerShare>
    <name>Aargau</name>
    <opportunityAccessLevel>None</opportunityAccessLevel>
    <accountAccessLevel>Edit</accountAccessLevel>
    <parentTerritory>Suiza</parentTerritory>
</Territory>
